name: Datadog Agent
slug: datadog-agent
description: >-
  This add-on runs the full Datadog Agent on Home Assistant.
  It monitors CPU, memory, disk, network, and Docker metrics, and exposes a DogStatsD collector
  for the Home Assistant Datadog integration.
url: "https://github.com/rapdev-io/addon-datadog-agent"
version: 1.0.0
startup: services
boot: auto

arch:
  - aarch64
  - armv7
  - amd64

# If we want to monitor everything, we need access to everything.
host_network: true
host_pid: true
full_access: true

ports:
# DogStatsD
  8125/udp: 8125

options:
  api_key: ""
  site: "datadoghq.com"

schema:
  api_key: str
  site: str?

environment:
  DD_DOGSTATSD_NON_LOCAL_TRAFFIC: "true"

# mounting host Docker socket enables Docker monitoring
map:
  docker: /var/run/docker.sock

